server:
  port: 8001
  servlet:
    context-path: /ocr
spring:
  datasource:


  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml


